# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/venkataravuri"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "X"
url = "https://x.com/ravuri"

[social.params]
icon = "brand-twitter"
